import React from 'react';

function About() {
    return (
        <section className='my-3' id="about">
            <h2 id="about-header" className='text-dark bg-primary p-2 display-inline-block'>About Me</h2>
            <div>
                <img id="about-image" src={require(`../../assets/images/patrick.jpg`)} alt="Patrick Regan" />
                <p>I grew up in Louisiana so I have an instinctual love of cajun food. One of my favorites is boudin, pronounced "BOO-dan", a spicy pork, rice and vegtable mixture stuffed into a sausage casing. The links are easy to eat and great for breakfast or a late night snack. It's definately cajun comfort food and if you drive from Beaumont to New Orleans, every gas station in between will probably have great tasting boudin.</p>
                <p>I'm half Korean so I love Korean food too, especially Korean BBQ. The BBQ is great, but what I love most are the small side dishes of vegetables called Banchan. They come out at the start of the meal and give you something to munch on before the main course. Marinated cucumbers, bean sprouts, and seaweed salad are some examples and you eat them with steamed rice. There are many more types of banchan and each restaurant may serve something different depending on what vegetables are in season.</p>
                <p>After high school I joined the Navy and was stationed in Pearl Harbor, Hawaii. In my free time I learned to surf and went to college at Hawaii Pacific University where I earned a bachelors degree in Business Administration. I learned about databases in one of my computer courses and that got me interested in Information Technology.</p>
                <p>After the military I found my way to Austin, Texas and started my career in Information Technology (IT). My first IT job was a Systems Support Specialist at the Texas Department of Human Services. I learned how to make websites dynamic with data from databases using Cold Fusion and SQL Server. Then I moved on to Austin Community College where I developed a web-based budget system for college administrators to allocate funds to each department for the year. I built it with Active Server Pages and SQL Server. After a few years I moved into a Database administrator position, then I decided to move on to the private sector.</p>
                <p>My first job in the private sector was a contractor working for Dell. My job was to support their order processing system at one of the fulfillment centers in Austin. The system was a web application running on Active Server Pages and SQL Server. It ingested and correlated data from several other Dell databases and let the pickers on the floor know what items to put into each shipping box that came down the line. This job was a night and day difference from my job at the community college or the state agency. Those jobs were very laid back and low stress. This new job was higher stakes because there were about 100 employees at any time depending on the system to do their job and get orders shipped. And when the sytem was down they could not work so they were getting paid to do nothing. It was on one of the incident calls where I learned how incident managers calculate impact of the system being down. It was tough and stressful but it was great experience for my next job.</p>
                <p>My career at Visa started as a contractor supporting Verified by Visa. I was responsible for change and incident management. After 10 months as a contractor I converted to a full time employee and have been at Visa ever since. I have been at Visa for over 15 years and have been a Programmer Analyst, Systems Engineer, Manager, Director and currently a Sr. Director of Product Reliability Engineering. Visa is a great place to work and I am very proud to be a part of it.</p>
                <p>I am continually learning new things to better myself and am currently enrolled in the UT Coding Bootcamp. I hope my work below shows what I have learned while progressing through the course.</p>
            </div>
        </section>
    )
}

export default About;